apiVersion: v1
kind: Secret
metadata:
  name: citizenportal-secrets
type: Opaque
stringData:
  db-connection: "Server=db,1433;Database=CitizenPortalDb;User Id=sa;Password=CitizenPortal123!;TrustServerCertificate=True;"
  jwt-key: "CitizenPortalSuperSecretKey123!@@#SuperLong"